### ISSUE TITLE
Wrong position of RSS feed icon on mobile

### ISSUE THREAD

**Issue by jcubic** [amiyasahu/Donut#105]
Not sure if this is error or intentional but it don't look good on mobile.

![donut_01](https://user-images.githubusercontent.com/280241/57125401-9472a800-6d89-11e9-8d8c-8ad9b82c9bf5.png)

this can be fixed by just using:
```css
.page-title {
    position: relative;
    padding: 30px 40px 30px 0;
}
.qa-rss-feed {
   bottom: 30px;
}
```

![Donut_02](https://user-images.githubusercontent.com/280241/57125473-dc91ca80-6d89-11e9-9e40-ff8dc1ce96e8.png)

the other option is to align to top (`top: 30px`).
