### ISSUE TITLE
text overlap box

### ISSUE THREAD

**Issue by Soeldner** [amiyasahu/Donut#44]
![screenshot](https://cloud.githubusercontent.com/assets/1868211/12966497/31d43b34-d05f-11e5-8547-1240beec4497.jpg)

quick and dirty change part

`````` css
/* Answers and views count */
.qa-a-count {
  border: 1px solid #d6e9c6;
  color: #3c763d;
  float: left;
  width: 60px;
  height: 60px;
  text-align: center;
  margin-right: 5px;
  padding: 0;
  border-radius: 5px;
}```

into

```css
/* Answers and views count */
.qa-a-count {
  border: 1px solid #d6e9c6;
  color: #3c763d;
  float: left;
  min-width: 60px;
  width: auto;
  height: auto;
  text-align: center;
  margin-right: 5px;
  padding: 0;
  border-radius: 5px;
}```

works for me. maybe it will help someone else.
``````
